spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=admin&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /manager
  port: 8081
